language: node_js
node_js:
  - "4"

services:
  - rabbitmq
  - memcached

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - export CXX="g++-4.8"

deploy:
  provider: npm
  email: cloudservices@loyalty.co.nz
  api_key:
    secure: "BphW6Axi25jTvvxGsgfKC3BkAS9AHxc0mLxK46pf8tQNyeSoIkc1NAflNLVs2tqABAHqo0SdkvKMIabGgR/HlKx6vJNTnwcRNBPRDS595d79gPnsosohBRVuVJ7F8yJdZ9klYrbYzHC8F6RabrrdX5iXVl7/joa1Yoy1DVLaPBvFQo9bTQdrgA2DuPxT3wfcErh34IIOYvW5AB1cpH927rEQbxvKFLDLSzGypbj9uW6YTFX0NUAj5HTR6U+2kjogHu3FJ5Gzdbra2E3zpEFhvvIBjGblbEQs05G46xIJTSa5SXf7acCnvrzL9mxU5uTVMGacQhkUwD5UjXTGiqEPzOghul9Ufo/OcH9n9Xuo67WQnCwP95uKDrh2MkScPbxweMgnBlSuqvMSyQ/+EdHJ/mvzww70sHAJMnGrj/qNPuIaBJJSP3YG2O4KgImEm5+wiserPRGfAktFP4rUCsyzY3mWtb0r4NGpOapKYL8fqAv3iF3mmruX8bTKpHfM83TSEYTcFBdpyV27qlITWyQDgOXv6Z1egxDLnEpqugsdFSV6RVFDp9+Q0sw6rMvvJluZsexap0aUujRzdP2S1dhH8uiiII6+retd9wkNZHsmsEJSeMBYksnB72bc4BW3EQ3ihtY3DvpL+WFfxtYZM5iTHVhsoIl+83SaVrBR/amKAOw="
  on:
    tags: true
