services:
  - rabbitmq
  - memcached

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

language: node_js

compiler:
  - gcc

before_install:
  - export CXX="g++-4.8"

# after_success:
#   - codeclimate-test-reporter < coverage/lcov.info

node_js:
  - "0.12.7"

# TODO: codeclimate-repo-token
