language: node_js
node_js:
- 8.11.4
services:
- rabbitmq
- memcached
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - rabbitmq-server
cache:
  directories:
  - node_modules
before_install:
- export CXX="g++-4.8"
before_script:
- npm install -g npm@6.2.0
- npm install -g audit-filter
script:
- npm audit --json | audit-filter --nsp-config=.nsprc --audit=-
- npm test
deploy:
  provider: npm
  email: cloudservices@loyalty.co.nz
  api_key:
    secure: UZqRabt/ckHJyvdroyqv697n0wyJANGdSjh1zPlstTzUAfFh0CM94ZZOXl3xDHeHxbV4KYg98K48rdq5gsZEGT4DAmygM1MJHYUMsFIve0pI25VpJZuig845XsCPoXfPuHGy1IzIFMLzf1jqLvgjE9XyaAOQWVfiDBSl7FpF5eMWUb6DJDCFyH927MQwCxaaCrgQnhBGvgZCH7i18mV4QU7ExxVv4eRtALMR67ICUNTu/edgRaEDYgP8g2lwUs4p2Veetwz+v2Ew4uJ20+gtK4LkBl9P2Zk3NpoyLcNWTdiDLdvhLzBr3swE61cumXm+6pMSRUSYlfxX9u9AgkybjaHQu/QWwOW0E6QOT95hXXrzVMwEjZnzx4Ov1U2NGZC/gVTdtL3wPaNwcv+n6T8ipa/FhtzNCCGg1d6ecaV6FwjQdD4nYCT3qL1/0zjOf86riHy7yXSME/Jzj3SdQ9XwFT9I6vouONcNQTrxTcWvP16SB8MUM8EXONNDmDJ3Jb4D0vmdchcLYBW0jUWIRdC0e/X1t3h50W0Kex2P+Acrpr1hQN/KIFfoAGDI+k2LkBCNiwF6UK6OXsJU50L495URp3IdBzUWRo1F1cQ1C81NOWfWtF1/CK52Qv3Z08k8tJYLNSpsdq+wk8zgIx7DgozW5tYvPpue0kJvdtanhcz34s8=
  on:
    tags: true
