name: OSV-Scanner

on:
  pull_request:
    branches: [master]

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV-Scanner
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src ghcr.io/google/osv-scanner:latest \
          --output=results.json \
          --format=table \
          --config=osv-config.toml \
          .

        continue-on-error: true

      - name: Print scan results
        if: always()
        run: |
            if [ -f results.json ]; then
            cat results.json
            exit 1
            else
            echo "results.json file not found. The scan may have failed to generate output."
            fi