name: OSV-Scanner

on:
  pull_request:
    branches: [master]

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Run osv-scanner
        uses: google/osv-scanner-action@v1.7.1
        with:
          scan-args: |-
            --config=osv-config.toml